//ERRORS
export const SET_ERRORS = 'SET_ERRORS'

//CATEGORIES
export const SET_CATEGORIES = 'SET_CATEGORIES'

//BRANDS
export const SET_BRANDS = 'SET_BRANDS'

//SIZES
export const SET_SIZES = 'SET_SIZES'